import { nanoid } from 'nanoid';
import { FlashcardSetData } from './interfaces';

const decks: FlashcardSetData[] = [
  {
    id: nanoid(),
    setNumber: 1,
    cards: [
      {
        id: nanoid(),
        cardNumber: 1,
        furigana: ' ハロー',
        english: 'Hello',
        japanese: 'こんにちは。',
      },
      {
        id: nanoid(),
        cardNumber: 2,
        furigana: 'ハウ　アー　ユー',
        english: 'How are you?',
        japanese: '元気ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 3,
        furigana: 'アイ　アム　グッドゥ',
        english: 'I am good.',
        japanese: '私は元気です。',
      },
      {
        id: nanoid(),
        cardNumber: 4,
        furigana: 'アイ　アム　オウケイ',
        english: 'I am OK.',
        japanese: '私はまあまあです。',
      },
      {
        id: nanoid(),
        cardNumber: 5,
        furigana: 'アイ　アム　タイアードゥ',
        english: 'I am tired.',
        japanese: '私は疲れています。',
      },
      {
        id: nanoid(),
        cardNumber: 6,
        furigana: 'ハウ　メニイ　アプルズ　ドゥー　ユー　ヒャブ',
        english: '  How many apples do you have?',
        japanese: '  あなたはリンゴを何個持っていますか。',
      },
      {
        id: nanoid(),
        cardNumber: 7,
        furigana: 'アイ　ヒャブ　スリー',
        english: 'I have three.',
        japanese: '私は３個持っています。',
      },
      {
        id: nanoid(),
        cardNumber: 8,
        furigana: 'ドゥー　ユー　ライク　レッドゥ',
        english: 'Do you like red?',
        japanese: 'あなたは赤色が好きですか。',
      },
      {
        id: nanoid(),
        cardNumber: 9,
        furigana: 'イエス　アイ　ドゥ',
        english: 'Yes, I do.',
        japanese: 'はい、好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 10,
        furigana: 'ノー　アイ　ドントゥ',
        english: "No, I don't.",
        japanese: 'いいえ、好きで はありません。',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 2,
    cards: [
      {
        id: nanoid(),
        cardNumber: 11,
        furigana: 'アイ　ライク　レッドゥ',
        english: 'I like red',
        japanese: '私は赤が好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 12,
        furigana: 'アイ　ドントゥ　ライク　レッド',
        english: "I don't like red.",
        japanese: '私は赤が好きではありません。',
      },
      {
        id: nanoid(),
        cardNumber: 13,
        furigana: '（フ）ワットゥ　スポートゥ　ドゥ　ユー　ライク',
        english: 'What sport do you like?',
        japanese: 'あなたはどんなスポーツが好きですか。',
      },
      {
        id: nanoid(),
        cardNumber: 14,
        furigana: 'アイ　ライク　テニス',
        english: 'I like tennis.',
        japanese: '  私はテニスが好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 15,
        furigana: '（フ）ワッツ　ズィス',
        english: "What's this?",
        japanese: 'これは何ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 16,
        furigana: 'イッツ　ア　バナナ',
        english: "It's a banana.",
        japanese: 'それはバナナです。',
      },
      {
        id: nanoid(),
        cardNumber: 17,
        furigana: 'フー　アー　ユー',
        english: 'Who are you?',
        japanese: 'あなたは誰ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 18,
        furigana: 'アイ　アム　ア　マンキー',
        english: 'I am a monkey.',
        japanese: '私はサルです。',
      },
      {
        id: nanoid(),
        cardNumber: 19,
        furigana: 'アー　ユー　ア　カウ',
        english: 'Are you a cow?',
        japanese: ' あなたは牛ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 20,
        furigana: 'イエス　アイ　アム',
        english: 'Yes, I am.',
        japanese: 'はい、そうです。',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 3,
    cards: [
      {
        id: nanoid(),
        cardNumber: 21,
        furigana: 'ノー　アイム　ノットゥ',
        english: "No, I'm not",
        japanese: 'いいえ、ちがいます。',
      },
      {
        id: nanoid(),
        cardNumber: 22,
        furigana: 'ズィス　イズ　フォー　ユー',
        english: 'This is for you.',
        japanese: 'これはあなたのための物です。',
      },
      {
        id: nanoid(),
        cardNumber: 23,
        furigana: 'センキュー',
        english: 'Thank you.',
        japanese: 'ありがとう。',
      },
      {
        id: nanoid(),
        cardNumber: 24,
        furigana: 'グッ(ドゥ)　モーニング',
        english: 'Good morning.',
        japanese: 'おはようございます。',
      },
      {
        id: nanoid(),
        cardNumber: 25,
        furigana: 'グッ(ドゥ)　アフタヌーン',
        english: 'Good afternoon.',
        japanese: 'こんにちは。(午後)',
      },
      {
        id: nanoid(),
        cardNumber: 26,
        furigana: 'グッ(ドゥ)　イーブニング',
        english: 'Good evening.',
        japanese: 'こんばんは。',
      },
      {
        id: nanoid(),
        cardNumber: 27,
        furigana: 'グッ(ドゥ)　ナイトゥ',
        english: 'Good night.',
        japanese: 'おやすみなさい。',
      },
      {
        id: nanoid(),
        cardNumber: 28,
        furigana: 'グッ(ドゥ)　バイ',
        english: 'Good bye.',
        japanese: 'さようなら。',
      },
      {
        id: nanoid(),
        cardNumber: 29,
        furigana: 'ハウズ　ザ　ウエザー',
        english: "How's the weather?",
        japanese: '天気はどうですか。',
      },
      {
        id: nanoid(),
        cardNumber: 30,
        furigana: 'イッツ　サニー',
        english: "It's sunny.",
        japanese: '晴れです',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 4,
    cards: [
      {
        id: nanoid(),
        cardNumber: 31,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 32,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 33,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 34,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 35,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 36,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 37,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 38,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 39,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 40,
        furigana: '',
        english: '',
        japanese: '',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 5,
    cards: [
      {
        id: nanoid(),
        cardNumber: 41,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 42,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 43,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 44,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 45,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 46,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 47,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 48,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 49,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 50,
        furigana: '',
        english: '',
        japanese: '',
      },
    ],
  },
];

export default decks;
