import type { FlashcardSet } from "@/types";

let seedId = 0;
const makeSeedId = () => `seed-${++seedId}`;

const decks: FlashcardSet[] = [
  {
    id: makeSeedId(),
    setNumber: 1,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 1,
        furigana: ' ハロー',
        english: 'Hello',
        japanese: 'こんにちは。',
      },
      {
        id: makeSeedId(),
        cardNumber: 2,
        furigana: 'ハウ　アー　ユー',
        english: 'How are you?',
        japanese: '元気ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 3,
        furigana: 'アイ　アム　グッドゥ',
        english: 'I am good.',
        japanese: '私は元気です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 4,
        furigana: 'アイ　アム　オウケイ',
        english: 'I am OK.',
        japanese: '私はまあまあです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 5,
        furigana: 'アイ　アム　タイアードゥ',
        english: 'I am tired.',
        japanese: '私は疲れています。',
      },
      {
        id: makeSeedId(),
        cardNumber: 6,
        furigana: 'ハウ　メニイ　アプルズ　ドゥー　ユー　ヒャブ',
        english: '  How many apples do you have?',
        japanese: '  あなたはリンゴを何個持っていますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 7,
        furigana: 'アイ　ヒャブ　スリー',
        english: 'I have three.',
        japanese: '私は３個持っています。',
      },
      {
        id: makeSeedId(),
        cardNumber: 8,
        furigana: 'ドゥー　ユー　ライク　レッドゥ',
        english: 'Do you like red?',
        japanese: 'あなたは赤色が好きですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 9,
        furigana: 'イエス　アイ　ドゥ',
        english: 'Yes, I do.',
        japanese: 'はい、好きです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 10,
        furigana: 'ノー　アイ　ドントゥ',
        english: "No, I don't.",
        japanese: 'いいえ、好きではありません。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 2,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 11,
        furigana: 'アイ　ライク　レッドゥ',
        english: 'I like red',
        japanese: '私は赤が好きです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 12,
        furigana: 'アイ　ドントゥ　ライク　レッド',
        english: "I don't like red.",
        japanese: '私は赤が好きではありません。',
      },
      {
        id: makeSeedId(),
        cardNumber: 13,
        furigana: '（フ）ワットゥ　スポートゥ　ドゥ　ユー　ライク',
        english: 'What sport do you like?',
        japanese: 'あなたはどんなスポーツが好きですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 14,
        furigana: 'アイ　ライク　テニス',
        english: 'I like tennis.',
        japanese: '  私はテニスが好きです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 15,
        furigana: '（フ）ワッツ　ズィス',
        english: "What's this?",
        japanese: 'これは何ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 16,
        furigana: 'イッツ　ア　バナナ',
        english: "It's a banana.",
        japanese: 'それはバナナです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 17,
        furigana: 'フー　アー　ユー',
        english: 'Who are you?',
        japanese: 'あなたは誰ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 18,
        furigana: 'アイ　アム　ア　マンキー',
        english: 'I am a monkey.',
        japanese: '私はサルです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 19,
        furigana: 'アー　ユー　ア　カウ',
        english: 'Are you a cow?',
        japanese: ' あなたは牛ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 20,
        furigana: 'イエス　アイ　アム',
        english: 'Yes, I am.',
        japanese: 'はい、そうです。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 3,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 21,
        furigana: 'ノー　アイム　ノットゥ',
        english: "No, I'm not",
        japanese: 'いいえ、ちがいます。',
      },
      {
        id: makeSeedId(),
        cardNumber: 22,
        furigana: 'ズィス　イズ　フォー　ユー',
        english: 'This is for you.',
        japanese: 'これはあなたのための物です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 23,
        furigana: 'センキュー',
        english: 'Thank you.',
        japanese: 'ありがとう。',
      },
      {
        id: makeSeedId(),
        cardNumber: 24,
        furigana: 'グッ(ドゥ)　モーニング',
        english: 'Good morning.',
        japanese: 'おはようございます。',
      },
      {
        id: makeSeedId(),
        cardNumber: 25,
        furigana: 'グッ(ドゥ)　アフタヌーン',
        english: 'Good afternoon.',
        japanese: 'こんにちは。(午後)',
      },
      {
        id: makeSeedId(),
        cardNumber: 26,
        furigana: 'グッ(ドゥ)　イーブニング',
        english: 'Good evening.',
        japanese: 'こんばんは。',
      },
      {
        id: makeSeedId(),
        cardNumber: 27,
        furigana: 'グッ(ドゥ)　ナイトゥ',
        english: 'Good night.',
        japanese: 'おやすみなさい。',
      },
      {
        id: makeSeedId(),
        cardNumber: 28,
        furigana: 'グッ(ドゥ)　バイ',
        english: 'Good bye.',
        japanese: 'さようなら。',
      },
      {
        id: makeSeedId(),
        cardNumber: 29,
        furigana: 'ハウズ　ザ　ウエザー',
        english: "How's the weather?",
        japanese: '天気はどうですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 30,
        furigana: 'イッツ　サニー',
        english: "It's sunny.",
        japanese: '晴れです',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 4,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 31,
        furigana: 'イッツ　クラウディー',
        english: "It's cloudy.",
        japanese: '曇りです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 32,
        furigana: 'イッツ　レイニー',
        english: "It's rainy.",
        japanese: '雨です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 33,
        furigana: 'イッツ　スノーイー',
        english: "It's snowy.",
        japanese: '雪です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 34,
        furigana: '（フ）ワット　デイ　イズ　イットゥ',
        english: 'What day is it?',
        japanese: '何曜日ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 35,
        furigana: 'イッツ　マンデイ',
        english: "It's Monday.",
        japanese: '月曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 36,
        furigana: 'イッツ　チューズデイ',
        english: "It's Tuesday.",
        japanese: '火曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 37,
        furigana: 'イッツ　ウエンズデイ',
        english: "It's Wednesday.",
        japanese: '水曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 38,
        furigana: 'イッツ　サーズデイ',
        english: "It's Thursday.",
        japanese: '木曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 39,
        furigana: 'イッツ　フライデイ',
        english: "It's Friday.",
        japanese: '金曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 40,
        furigana: 'イッツ　サタデイ',
        english: "It's Saturday.",
        japanese: '土曜日です。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 5,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 41,
        furigana: 'イッツ　サンデイ',
        english: "It's Sunday.",
        japanese: '日曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 42,
        furigana: '（フ）ワットゥ　タイム　イズ　イットゥ',
        english: 'What time is it?',
        japanese: '何時ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 43,
        furigana: 'イッツ　ファイブ　ピー エム',
        english: "It's five p.m.",
        japanese: '午後５時です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 44,
        furigana: 'イッツ　ナイン　エイ　エム',
        english: "It's nine a.m.",
        japanese: '午前９時です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 45,
        furigana: 'ドゥー　ユー　ヒャブ　ア　ペン',
        english: 'Do you have a pen?',
        japanese: 'あなたはペンを持っていますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 46,
        furigana: 'イエス　アイ　ドゥー',
        english: 'Yes, I do.',
        japanese: 'はい、持っています。',
      },
      {
        id: makeSeedId(),
        cardNumber: 47,
        furigana: 'ノー　アイ　ドントゥ',
        english: "No, I don't.",
        japanese: 'いいえ、持っていません。',
      },
      {
        id: makeSeedId(),
        cardNumber: 48,
        furigana: '（フ）ワットゥ　ドゥー　ユー　ワントゥ',
        english: 'What do you want?',
        japanese: 'あなたは何が欲しいですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 49,
        furigana: 'アイ　ワントゥ　ア　ピーチ',
        english: 'I want a peach.',
        japanese: '私は桃が欲しいです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 50,
        furigana: 'ヒヤ　ユー　アー',
        english: 'Here you are.',
        japanese: 'はい、どうぞ。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 6,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 51,
        furigana: 'ゴー　ストゥレイトゥ',
        english: 'Go straight.',
        japanese: 'まっすぐに行きなさい。',
      },
      {
        id: makeSeedId(),
        cardNumber: 52,
        furigana: 'ターン　ライトゥ',
        english: 'Turn right.',
        japanese: '右に曲がりなさい。',
      },
      {
        id: makeSeedId(),
        cardNumber: 53,
        furigana: 'ターン　レフトゥ',
        english: 'Turn left.',
        japanese: '左に曲がりなさい。',
      },
      {
        id: makeSeedId(),
        cardNumber: 54,
        furigana: 'ズィス　イズ　マイ　フェイバリットゥ　プレイス',
        english: 'This is my favorite place.',
        japanese: 'これは私の大好きな場所です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 55,
        furigana: 'ズィス　イズ　マイ　デイ',
        english: 'This is my day.',
        japanese: 'これは私の１日の生活です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 56,
        furigana: 'スィー　ユー　レイター',
        english: 'See you later.',
        japanese: 'またね。',
      },
      {
        id: makeSeedId(),
        cardNumber: 57,
        furigana: 'フェン　イズ　ユア　バースデイ',
        english: 'When is your birthday?',
        japanese: 'あなたの誕生日はいつですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 58,
        furigana: 'イッツ　ジャニゥアリィ　ナインティーンス',
        english: "It's January 19th.",
        japanese: 'それは1月19日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 59,
        furigana:
          '（フ）ワットゥ　ドゥー　ユー　ワントゥ　フォー　ユア　バースデイ',
        english: 'What do you want for your birthday?',
        japanese: 'あなたは誕生日に何が欲しいですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 60,
        furigana: 'アイ　ワントゥ　ア　サッカー　ボール',
        english: 'I want a soccer ball.',
        japanese: '私はサッカーボールが欲しいです。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 7,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 61,
        furigana: 'アイ　キャン　ラン',
        english: 'I can run.',
        japanese: '私は走ることができます。',
      },
      {
        id: makeSeedId(),
        cardNumber: 62,
        furigana: 'アイ　キャントゥ　ジャンプ',
        english: "I can't jump.",
        japanese: '私は飛ぶことができません。',
      },
      {
        id: makeSeedId(),
        cardNumber: 63,
        furigana: 'キャン　ユー　プレイ　ザ　バイオリン',
        english: 'Can you play the violin?',
        japanese: 'あなたはバイオリンを弾けますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 64,
        furigana: 'イエス, アイ　キャン. / ノー, アイ　キャントゥ',
        english: "Yes, I can./ No, I can't.",
        japanese: 'はい、弾けます。いいえ、弾けません。',
      },
      {
        id: makeSeedId(),
        cardNumber: 65,
        furigana: 'キャン　ユー　ドゥ　ズィス',
        english: 'Can you do this?',
        japanese: 'これができますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 66,
        furigana: 'ヒイ　イズ　ア　ベイカー',
        english: 'He is a baker.',
        japanese: '彼はパン屋です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 67,
        furigana: 'フー　イズ　シー',
        english: 'Who is she ?',
        japanese: '彼女は誰ですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 68,
        furigana: 'シー　イズ　ア　ティーチャー',
        english: 'She is a teacher.',
        japanese: '彼女は先生です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 69,
        furigana: 'ヒイ　イズ　グッドゥ　アットゥ　ベイスボール',
        english: 'He is good at baseball.',
        japanese: '彼は野球が得意です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 70,
        furigana: '（フ）ワットゥ　タイム　ドゥ　ユー　イートゥ　ディナー',
        english: 'What time do you eat dinner?',
        japanese: 'あなたは何時に夕食を食べますか。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 8,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 71,
        furigana: 'アイ　ユージュアリイ　イートゥ　ディナー　アットゥ　セブン',
        english: 'I usually eat dinner at seven.',
        japanese: '私はたいてい７時に夕食を食べます。',
      },
      {
        id: makeSeedId(),
        cardNumber: 72,
        furigana: '（フ）エン　ドゥー　ユー　ヒャブ　イングリッシュ',
        english: 'When do you have English?',
        japanese: '英語はいつありますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 73,
        furigana: 'オン　ウエンズデイズ',
        english: 'On Wednesdays.',
        japanese: '毎週水曜日です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 74,
        furigana: '（フ）ワットゥ　サブジェクトゥ　ドゥー　ユー　ライク',
        english: 'What subjects do you like?',
        japanese: 'どんな教科が好きですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 75,
        furigana: '（フ）ワットゥ　ドゥー　ユー　ドゥー　オン　チューズデイ',
        english: 'What do you doon Tuesday?',
        japanese: 'あなたは火曜日に何をしますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 76,
        furigana: 'アイ　プレイ　サッカー　オン　チューズデイ',
        english: 'I play soccer on Tuesday.',
        japanese: '私は火曜日にサッカーをします。',
      },
      {
        id: makeSeedId(),
        cardNumber: 77,
        furigana: '（フ）ウェア　イズ　ザ　バードゥ',
        english: 'Where is the bird?',
        japanese: 'その鳥はどこにいますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 78,
        furigana: 'イティ　イズ　オン（イン、バイ、　アンダー）　ザ　ボックス',
        english: 'It is on(in,by,under) the box.',
        japanese: 'それはその箱の上（中、そば、下）にいます。',
      },
      {
        id: makeSeedId(),
        cardNumber: 79,
        furigana: 'ターン　ライトゥ　アットゥ　ザ　セカンド　コーナー',
        english: 'Turn right at the second corner.',
        japanese: '２番目の角を右に曲がって。',
      },
      {
        id: makeSeedId(),
        cardNumber: 80,
        furigana: 'ユー　キャン　スィー　イットゥ　オン　ユア　レフトゥ',
        english: 'You can see it on your left.',
        japanese: 'それは左側にあります。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 9,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 81,
        furigana: '（フ）ウェア　ドゥー　ユー　ワントゥー　ゴー',
        english: 'Where do you want to go?',
        japanese: 'あなたはどこに行きたいですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 82,
        furigana: 'アイ　ワントゥ　ゴー　トゥ　ニュー　ジーランドゥ',
        english: 'I want to go to New Zealand.',
        japanese: '私はニュージーランドに行きたいです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 83,
        furigana: '（フ）ワットゥ　ドゥー　ユー　ワントゥー　イートゥ',
        english: 'What do you want to eat?',
        japanese: 'あなたは何を食べたいですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 84,
        furigana: 'アイ　ワントゥー　イートゥ　ピッツァ',
        english: 'I want to eat pizza.',
        japanese: '私はピザが食べたいです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 85,
        furigana: 'ウイ　アー　フロム　ジャパン',
        english: 'We are from Japan.',
        japanese: '私たちは日本出身です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 86,
        furigana: 'フェン　ドゥ　ユー　ヒャブ　ザ　スクール　スポーツ　デイ',
        english: 'When do you have the school sports day?',
        japanese: 'いつ運動会がありますか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 87,
        furigana: 'イン　セプテンバー',
        english: 'In September.',
        japanese: '９月にあります。',
      },
      {
        id: makeSeedId(),
        cardNumber: 88,
        furigana: 'アイ　ウエントゥー　ヒロシマ',
        english: 'I went to Hiroshima.',
        japanese: '私は広島に行きました。',
      },
      {
        id: makeSeedId(),
        cardNumber: 89,
        furigana: 'アイ　ソー　ミヤジマ',
        english: 'I saw Miyajima.',
        japanese: '私は宮島を見ました。',
      },
      {
        id: makeSeedId(),
        cardNumber: 90,
        furigana: 'アイ　エイトゥ　モミジマンジュー',
        english: 'I ate momijimanju.',
        japanese: '私はもみじまんじゅうを食べました。',
      },
    ],
  },
  {
    id: makeSeedId(),
    setNumber: 10,
    cards: [
      {
        id: makeSeedId(),
        cardNumber: 91,
        furigana: 'アイ　エンジョイドゥ　ショッピング',
        english: 'I enjoyed shopping.',
        japanese: '私は買い物を楽しみました。',
      },
      {
        id: makeSeedId(),
        cardNumber: 92,
        furigana: 'ザ　ジィラーフ　イズ　トール',
        english: 'The giraffe is tall.',
        japanese: 'そのキリンは背が高いです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 93,
        furigana: 'ゼイ　アー　スペシャル　トゥ　ミイ',
        english: 'They are special to me.',
        japanese: 'それらは私には特別です。',
      },
      {
        id: makeSeedId(),
        cardNumber: 94,
        furigana: 'ハウ　マッチ　イズ　イットゥ',
        english: 'How much is it?',
        japanese: 'それはいくらですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 95,
        furigana: 'イッツ　エイトゥ　ダラーズ',
        english: "It's 8 dollars.",
        japanese: '８ドルです。',
      },
      {
        id: makeSeedId(),
        cardNumber: 96,
        furigana: 'イティ　イズ　イエロー イトゥ　ワズ　グリーン',
        english: 'It is yellow. It was green.',
        japanese: 'それは黄色です。それは緑色でした。',
      },
      {
        id: makeSeedId(),
        cardNumber: 97,
        furigana: '（フ）ワットゥ　ドゥ　ユー　ワントゥー　ビィー',
        english: 'What do you want to be?',
        japanese: 'あなたは何になりたいですか。',
      },
      {
        id: makeSeedId(),
        cardNumber: 98,
        furigana: 'アイ　ワントゥー　ビィー　ア　ドクター',
        english: 'I want to be a doctor.',
        japanese: '私はお医者さんになりたいです。',
      },
    ],
  },
];

export default decks;
