import { nanoid } from 'nanoid';
import { DecksType } from './interfaces';

const decks: DecksType = [
  {
    id: nanoid(),
    setNumber: 1,
    cards: [
      {
        id: nanoid(),
        cardNumber: 1,
        furigana: ' ハロー',
        english: 'Hello',
        japanese: 'こんにちは。',
      },
      {
        id: nanoid(),
        cardNumber: 2,
        furigana: 'ハウ　アー　ユー',
        english: 'How are you?',
        japanese: '元気ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 3,
        furigana: 'アイ　アム　グッドゥ',
        english: 'I am good.',
        japanese: '私は元気です。',
      },
      {
        id: nanoid(),
        cardNumber: 4,
        furigana: 'アイ　アム　オウケイ',
        english: 'I am OK.',
        japanese: '私はまあまあです。',
      },
      {
        id: nanoid(),
        cardNumber: 5,
        furigana: 'アイ　アム　タイアードゥ',
        english: 'I am tired.',
        japanese: '私は疲れています。',
      },
      {
        id: nanoid(),
        cardNumber: 6,
        furigana: 'ハウ　メニイ　アプルズ　ドゥー　ユー　ヒャブ',
        english: '  How many apples do you have?',
        japanese: '  あなたはリンゴを何個持っていますか。',
      },
      {
        id: nanoid(),
        cardNumber: 7,
        furigana: 'アイ　ヒャブ　スリー',
        english: 'I have three.',
        japanese: '私は３個持っています。',
      },
      {
        id: nanoid(),
        cardNumber: 8,
        furigana: 'ドゥー　ユー　ライク　レッドゥ',
        english: 'Do you like red?',
        japanese: 'あなたは赤色が好きですか。',
      },
      {
        id: nanoid(),
        cardNumber: 9,
        furigana: 'イエス　アイ　ドゥ',
        english: 'Yes, I do.',
        japanese: 'はい、好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 10,
        furigana: 'ノー　アイ　ドントゥ',
        english: "No, I don't.",
        japanese: 'いいえ、好きで はありません。',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 2,
    cards: [
      {
        id: nanoid(),
        cardNumber: 11,
        furigana: 'アイ　ライク　レッドゥ',
        english: 'I like red',
        japanese: '私は赤が好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 12,
        furigana: 'アイ　ドントゥ　ライク　レッド',
        english: "I don't like red.",
        japanese: '私は赤が好きではありません。',
      },
      {
        id: nanoid(),
        cardNumber: 13,
        furigana: '（フ）ワットゥ　スポートゥ　ドゥ　ユー　ライク',
        english: 'What sport do you like?',
        japanese: 'あなたはどんなスポーツが好きですか。',
      },
      {
        id: nanoid(),
        cardNumber: 14,
        furigana: 'アイ　ライク　テニス',
        english: 'I like tennis.',
        japanese: '  私はテニスが好きです。',
      },
      {
        id: nanoid(),
        cardNumber: 15,
        furigana: '（フ）ワッツ　ズィス',
        english: "What's this?",
        japanese: 'これは何ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 16,
        furigana: 'イッツ　ア　バナナ',
        english: "It's a banana.",
        japanese: 'それはバナナです。',
      },
      {
        id: nanoid(),
        cardNumber: 17,
        furigana: 'フー　アー　ユー',
        english: 'Who are you?',
        japanese: 'あなたは誰ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 18,
        furigana: 'アイ　アム　ア　マンキー',
        english: 'I am a monkey.',
        japanese: '私はサルです。',
      },
      {
        id: nanoid(),
        cardNumber: 19,
        furigana: 'アー　ユー　ア　カウ',
        english: 'Are you a cow?',
        japanese: ' あなたは牛ですか。',
      },
      {
        id: nanoid(),
        cardNumber: 20,
        furigana: 'イエス　アイ　アム',
        english: 'Yes, I am.',
        japanese: 'はい、そうです。',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 3,
    cards: [
      {
        id: nanoid(),
        cardNumber: 21,
        furigana: 'ゥ',
        english: 'd',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 22,
        furigana: 'イク　レッド',
        english: 'ike red.',
        japanese: 'りません。',
      },
      {
        id: nanoid(),
        cardNumber: 23,
        furigana: 'ポートゥ　ドゥ　ユー　ライク',
        english: 't do you like?',
        japanese: 'ーツが好きですか。',
      },
      {
        id: nanoid(),
        cardNumber: 24,
        furigana: 'ス',
        english: 'Inis.',
        japanese: 'きです。',
      },
      {
        id: nanoid(),
        cardNumber: 25,
        furigana: 'ィス',
        english: 'his?',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 26,
        furigana: 'ナ',
        english: 'anana.',
        japanese: '。',
      },
      {
        id: nanoid(),
        cardNumber: 27,
        furigana: '',
        english: 'you?',
        japanese: '。',
      },
      {
        id: nanoid(),
        cardNumber: 28,
        furigana: 'マンキー',
        english: 'onkey.',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 29,
        furigana: 'ウ',
        english: ' cow?',
        japanese: ' ',
      },
      {
        id: nanoid(),
        cardNumber: 30,
        furigana: '',
        english: '.',
        japanese: '',
      },
    ],
  },
  {
    id: nanoid(),
    setNumber: 4,
    cards: [
      {
        id: nanoid(),
        cardNumber: 31,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 32,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 33,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 34,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 35,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 36,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 37,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 38,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 39,
        furigana: '',
        english: '',
        japanese: '',
      },
      {
        id: nanoid(),
        cardNumber: 40,
        furigana: '',
        english: '',
        japanese: '',
      },
    ],
  },
];

export default decks;
